### ISSUE TITLE
When the highlight button in the node menu is clicked pathogen crashes

### ISSUE THREAD

**Issue by EcstaticPilot** [AnselChang/Pathogen4#34] opened 2023-06-17 18:42 UTC
clicking the highlight button of the node menu gives the error message

> AttributeError: 'CommandModel' object has no attribute 'highlight'

**Comment by EcstaticPilot** [comment] 2023-06-17 18:44
seems like I was on the wrong branch

**Comment by EcstaticPilot** [comment] 2023-06-17 18:47
turns out it was the right branch

**Comment by AnselChang** [comment] 2023-06-17 18:50
duplicate of #30

**Closed** 2023-06-24 18:02 UTC
Labels: bug, software, small
